In [1]:
import pandas as pd 
import numpy as np
import matplotlib.pyplot as plt
import tensorflow as tf


df = pd.read_csv("reviews_final_modelled.csv")

df.head()

id reviews.val.date  reviews.val.helpfulCount  reviews.val.id  \
0    3087       2008-06-11                         0            5865   
1  147399       2008-06-12                         1           12735   
2   82943       2008-06-12                         5           13384   
3  147399       2008-06-12                         2           14896   
4   54007       2008-06-14                         0           20148   

   careerOpportunities_rating  compBenefits_rating  cultureValues_rating  \
0                         4.0                  3.0                     0   
1                         5.0                  4.0                     0   
2                         4.0                  3.0                     0   
3                         2.0                  2.5                     0   
4                         3.5                  3.0                     0   

   overall_rating  seniorManagement_rating  worklifeBalance_rating  ...  \
0               4                      3.5                     3.0  ...   
1               5                      4.0                     3.5  ...   
2               4                      3.5                     1.5  ...   
3               2                      2.0                     3.5  ...   
4               3                      3.0                     4.0  ...   

  reviews.val.summaryPoints.outlook reviews.val.summaryPoints.recommend  \
0                                 0                                   1   
1                                 0                                   1   
2                                 0                                   0   
3                                 0                                   2   
4                                 0                                   0   

                       overview.industry            overview.sector  \
0              Biotech & Pharmaceuticals  Biotech & Pharmaceuticals   
1                 Research & Development          Business Services   
2             Food & Drink Manufacturing              Manufacturing   
3                 Research & Development          Business Services   
4  Electrical & Electronic Manufacturing              Manufacturing   

     header.employerName  gaTrackerData.empName  \
0           Compugen USA      Compugen (isreal)   
1                ManTech                ManTech   
2  The Coca-Cola Company  The Coca-Cola Company   
3                ManTech                ManTech   
4     Marvell Technology  Marvell Semiconductor   

                                      overall_review language rating_class  \
0  Good place to work, not for exit. Great workin...       en     Positive   
1  A top notch place to work for people in the hi...       en     Positive   
2  Great place to work (if you really love to wor...       en     Positive   
3  Mantech, willing to do anything for a buck.. T...       en     Negative   
4  just a job. not mutural in management level. l...       en      Neutral   

                                      cleaned_review  
0  good place not exit great envirement not focus...  
1  top notch place people hi tech defense service...  
2  great place really love long long hours great ...  
3  mantech willing anything buck large not set di...  
4  job not mutural management level leader market...  

[5 rows x 23 columns]

In [2]:
print(df['overall_review'].count(),'\n\n',df['overall_rating'].value_counts(),'\n\n',
      df['overall_review'].count()==df['overall_rating'].count())

69339 

 5    28731
4    18992
3    10241
1     6183
2     5192
Name: overall_rating, dtype: int64 

 True


In [4]:
rating = []
for i in df['overall_rating']:
        if i > 3 : rating.append(1)
        elif i > 2:  rating.append(0)
        else:       rating.append(-1)

df['overall_rating2'] = rating
    
df.head()

id reviews.val.date  reviews.val.helpfulCount  reviews.val.id  \
0    3087       2008-06-11                         0            5865   
1  147399       2008-06-12                         1           12735   
2   82943       2008-06-12                         5           13384   
3  147399       2008-06-12                         2           14896   
4   54007       2008-06-14                         0           20148   

   careerOpportunities_rating  compBenefits_rating  cultureValues_rating  \
0                         4.0                  3.0                     0   
1                         5.0                  4.0                     0   
2                         4.0                  3.0                     0   
3                         2.0                  2.5                     0   
4                         3.5                  3.0                     0   

   overall_rating  seniorManagement_rating  worklifeBalance_rating  ...  \
0               4                      3.5                     3.0  ...   
1               5                      4.0                     3.5  ...   
2               4                      3.5                     1.5  ...   
3               2                      2.0                     3.5  ...   
4               3                      3.0                     4.0  ...   

  reviews.val.summaryPoints.recommend                      overview.industry  \
0                                   1              Biotech & Pharmaceuticals   
1                                   1                 Research & Development   
2                                   0             Food & Drink Manufacturing   
3                                   2                 Research & Development   
4                                   0  Electrical & Electronic Manufacturing   

             overview.sector    header.employerName  gaTrackerData.empName  \
0  Biotech & Pharmaceuticals           Compugen USA      Compugen (isreal)   
1          Business Services                ManTech                ManTech   
2              Manufacturing  The Coca-Cola Company  The Coca-Cola Company   
3          Business Services                ManTech                ManTech   
4              Manufacturing     Marvell Technology  Marvell Semiconductor   

                                      overall_review language rating_class  \
0  Good place to work, not for exit. Great workin...       en     Positive   
1  A top notch place to work for people in the hi...       en     Positive   
2  Great place to work (if you really love to wor...       en     Positive   
3  Mantech, willing to do anything for a buck.. T...       en     Negative   
4  just a job. not mutural in management level. l...       en      Neutral   

                                      cleaned_review overall_rating2  
0  good place not exit great envirement not focus...               1  
1  top notch place people hi tech defense service...               1  
2  great place really love long long hours great ...               1  
3  mantech willing anything buck large not set di...              -1  
4  job not mutural management level leader market...               0  

[5 rows x 24 columns]

In [5]:
print(df['overall_review'].count(),'\n\n',df['overall_rating2'].value_counts(),'\n\n',
      df['overall_review'].count()==df['overall_rating2'].count())

69339 

  1    47723
-1    11375
 0    10241
Name: overall_rating2, dtype: int64 

 True


In [6]:
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.model_selection import train_test_split,StratifiedKFold
from sklearn.naive_bayes import MultinomialNB
from sklearn.naive_bayes import BernoulliNB
from sklearn import metrics
from sklearn.metrics import accuracy_score, classification_report
from sklearn.metrics import matthews_corrcoef

In [7]:
train_data = df
train_data.shape

(69339, 24)

In [8]:
vectorizer = CountVectorizer(analyzer="word", 
                             preprocessor=None, 
                             stop_words=None, 
                             ngram_range=(1,1),
                            max_features=5000)

In [9]:
train_data_features = vectorizer.fit_transform(df.cleaned_review)
train_data_features = train_data_features.toarray()

In [10]:
X = train_data_features
y = train_data.overall_rating2

In [11]:
print (X.shape) 
print (y.shape)

(69339, 5000)
(69339,)


In [12]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.25,random_state=123)

In [13]:
naive = MultinomialNB()
classifier = naive.fit(X_train,y_train)
predict = classifier.predict(X_test)

from sklearn.metrics import confusion_matrix

cm = confusion_matrix(predict,y_test)

print(cm)
print()
print(classification_report(predict,y_test))
print("MCC-Score:", matthews_corrcoef(y_test,predict))

[[1816  333  335]
 [ 725 1234 1741]
 [ 290  986 9875]]

              precision    recall  f1-score   support

          -1       0.64      0.73      0.68      2484
           0       0.48      0.33      0.39      3700
           1       0.83      0.89      0.85     11151

   micro avg       0.75      0.75      0.75     17335
   macro avg       0.65      0.65      0.64     17335
weighted avg       0.73      0.75      0.73     17335

MCC-Score: 0.49681148794747104


In [14]:
accuracy = cm.trace()/cm.sum()
print(accuracy)

0.7456013844822613


In [15]:
x = df.loc[:, df.columns != 'overall_rating2']
test_data_features = vectorizer.fit_transform(x.cleaned_review)
test_data_features = test_data_features.toarray()

In [16]:
y_pred_M = classifier.predict(test_data_features)

In [17]:
print(accuracy_score(y,y_pred_M))

0.7612022094348058


In [19]:
print ("There are %d exampes in our data"  % X.shape[0])
print ("We have made %d wrong predictions - these examples are:" % (y != y_pred_M).sum())  
error = []
for i in range(X.shape[0]):
    if (y[i] != y_pred_M[i]):
        error.append(i)
y_pred = pd.DataFrame(y_pred_M)
y_pred.columns = ["Predict"]

# error_1 = error[16:]
df['Predict'] = y_pred_M
df.iloc[error, 19:25]

There are 69339 exampes in our data
We have made 16558 wrong predictions - these examples are:


overall_review language  \
5      Experian is a decent place to work unless you ...       en   
6      Not a bad place to work. Challenging atmospher...       en   
7      Know where you're going?. lack of interdepartm...       en   
9      Too many managers !. Too many managers - many ...       en   
11     The stagnation of a company.. Company has had ...       en   
12     Management skills trails MDA's technical growt...       en   
13     MBI an ok place to work. Not a brand name comp...       en   
15     Nice place to work if you can stand pointy-hai...       en   
17     Good in theory..... uneven implementation. The...       en   
21     Heck of a boot camp for all starters with high...       en   
22     Maybe, Maybe Not. The best reasons will be tha...       en   
24     The 10,000 foot view. Working with very techni...       en   
27     Culture trumps strategy. It is discouraging to...       en   
28     Mediocrity in a field of many players. Cons\r\...       en   
29     Great atmosphere, good pay, but lacking in som...       en   
31     A pretty good place to work, but could be so m...       en   
34     Focus more on people development and welfare. ...       en   
36     Develpoment/Real Estate/Construction Co with n...       en   
37     Decent pay, easy going company. They allow emp...       en   
42     working in J&J. lack of transparency, lack of ...       en   
43     Don't rest on one's laurels, go forward, let p...       en   
44     JLL not ready for FM outsourcing deals. Very l...       en   
50     Kimberly Clark is a great place to work. It's ...       en   
53     I do not have inspiration for a facny headline...       en   
62     CSTS, keep your talents. Management team faile...       en   
64     Belkin is not the same company it was 10 years...       en   
69     Good place to move into business. Good career ...       en   
72     Pleasant, though not inspired. Anti-pragmatic,...       en   
74     Unfortunately Gallup is eroding their powerful...       en   
75     Incredibly high staff turnover, for good reaso...       en   
...                                                  ...      ...   
69174  There are much better companies to work for. T...       en   
69176  Good place to advance software career, too muc...       en   
69185  Software Engineer in Cloud Platform. Since I'm...       en   
69192  Junior Analyst. good working environment and c...       en   
69195  Good company. Cool manager no work pressure. G...       en   
69197  Great values. Good values, benefits due to not...       en   
69200  Good learning experience. Becomes quickly repe...       en   
69206  Software developer. Work life balance\r\nTrans...       en   
69222  Process Associate. A very good company with jo...       en   
69228  Nice Place to Work. Work Life Balance\r\nFlexi...       en   
69229  Good entry level scientist role. Good training...       en   
69237  Digital Marketing  - IBM. Good Culture and wor...       en   
69238  Cognos Senior Administrator. Benefits are very...       en   
69241  Not a culture encouraging creative work. - peo...       en   
69253  Assistant Vice President. Good benefits, bonus...       en   
69258  All over the place. Unstructured, poorly manag...       en   
69264  MB Review.. Upper management is not very good ...       en   
69268  Poor leadership. Poor management  with too man...       en   
69271  Not professional. The number two belittling yo...       en   
69272  Good place to work. Less work load, good salar...       en   
69275  Business Analyst at Regulatory Reform. Good pa...       en   
69276  Working in TD Ameritrade. Good Pay, flex hours...       en   
69283  Mixed Feelings. -constant fear of layoffs\r\n-...       en   
69291  No work life balance. - the environment is not...       en   
69295  Software Engineer III. Review process is worst...       en   
69297  Working for the big dog. Nobody does space lik...       en   
69300  Associate Software Engineer. - Be